import Link from 'next/link'
import { Lock } from '@phosphor-icons/react/dist/ssr'
// Structure-only teaser (section labels + file NAMES + counts, never content),
// generated by scripts/inject-premium.mjs on every build — real vault structure
// when reachable, a committed fallback snapshot on degraded builds. Counts are
// NEVER hardcoded here; everything below derives from this module.
import { BRAIN_TEASER } from '@/app/lib/andromeda-brain-teaser.generated'

const C = {
  surface: { base: '#0E0E0F', raised: '#141415', active: '#232325' },
  text: { primary: '#F5F5F5', secondary: '#A3A3A3', muted: '#9A9A9A', faint: '#6E6E6E' },
  accent: { 100: '#BAF8EC', 300: '#0FCFB2', 400: '#109380', 500: '#126059' },
  border: { subtle: '#212122', base: '#3E3E3F' },
}
const FONT = "var(--font-jetbrains-mono, 'JetBrains Mono Variable'), 'JetBrains Mono', monospace"

interface TeaserSection {
  id: string
  label: string
  files: readonly string[]
}

interface Props {
  tier: 'anonymous' | 'free' | 'premium'
  error?: boolean
}

export function BrainPaywall({ tier, error }: Props) {
  const isAnon = tier === 'anonymous'
  const sections = BRAIN_TEASER.sections as readonly TeaserSection[]

  return (
    <div
      style={{
        fontFamily: FONT,
        flex: 1,
        padding: '40px 48px',
        maxWidth: 720,
        color: C.text.secondary,
      }}
    >
      <style>{`
        .brain-cta:hover { background: ${C.accent[400]} !important; }
        .brain-lock-row { opacity: 0.32; }
        .brain-sign-in:hover { color: ${C.accent[300]} !important; }
      `}</style>

      {/* Header */}
      <div
        style={{
          fontSize: 9,
          letterSpacing: '0.22em',
          textTransform: 'uppercase',
          color: C.text.faint,
          marginBottom: 8,
        }}
      >
        Andromeda / Premium
      </div>
      <h1
        style={{
          fontSize: 20,
          fontWeight: 700,
          color: C.text.primary,
          margin: '0 0 4px',
          letterSpacing: '-0.01em',
        }}
      >
        Andromeda Brain
      </h1>
      <p style={{ fontSize: 13, color: C.text.muted, margin: '0 0 32px', lineHeight: 1.6 }}>
        The judgment layer for Andromeda. {BRAIN_TEASER.totalFiles} files covering
        foundations and per-component rules. The intelligence behind every build
        decision.
      </p>

      {error ? (
        <div
          style={{
            padding: '14px 18px',
            background: C.surface.raised,
            border: `1px solid ${C.border.base}`,
            fontSize: 12,
            color: C.text.muted,
            marginBottom: 32,
          }}
        >
          Brain files unavailable. Contact support or try again shortly.
        </div>
      ) : (
        /* Lock notice */
        <div
          style={{
            display: 'flex',
            alignItems: 'flex-start',
            gap: 14,
            padding: '16px 18px',
            background: C.surface.raised,
            border: `1px solid ${C.border.subtle}`,
            marginBottom: 36,
          }}
        >
          <Lock size={16} color={C.accent[300]} weight="regular" style={{ marginTop: 1, flexShrink: 0 }} />
          <div>
            <div style={{ fontSize: 12, color: C.text.primary, fontWeight: 600, marginBottom: 4 }}>
              Premium access required
            </div>
            <div style={{ fontSize: 11, color: C.text.muted, lineHeight: 1.6 }}>
              {isAnon
                ? 'Sign in and upgrade to Premium to access the full Andromeda Brain.'
                : 'Upgrade to Premium to access the full Andromeda Brain: every foundation and every per-component rule.'}
            </div>
          </div>
        </div>
      )}

      {/* Teaser: structure preview — sections + counts derive from BRAIN_TEASER */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 28, marginBottom: 40 }}>
        {sections.map((section) => (
          <div key={section.id}>
            <div
              style={{
                fontSize: 9,
                letterSpacing: '0.2em',
                textTransform: 'uppercase',
                color: C.text.faint,
                marginBottom: 10,
                display: 'flex',
                alignItems: 'center',
                gap: 8,
              }}
            >
              {section.label}
              <span
                style={{
                  fontSize: 8,
                  padding: '1px 6px',
                  background: C.surface.active,
                  color: C.accent[300],
                  letterSpacing: '0.12em',
                }}
              >
                {section.files.length} FILES
              </span>
            </div>
            <div
              className="brain-lock-row"
              style={{ display: 'flex', flexWrap: 'wrap', gap: '6px 12px' }}
            >
              {section.files.map((f) => (
                <div
                  key={f}
                  style={{
                    fontSize: 11,
                    color: C.text.muted,
                    padding: '3px 0',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 6,
                  }}
                >
                  <Lock size={9} color={C.text.faint} weight="regular" />
                  {f}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* CTA */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
        <Link
          href="/pricing"
          className="brain-cta"
          style={{
            display: 'inline-block',
            padding: '10px 24px',
            background: C.accent[300],
            color: C.surface.base,
            fontSize: 11,
            fontWeight: 700,
            letterSpacing: '0.1em',
            textTransform: 'uppercase',
            textDecoration: 'none',
            fontFamily: FONT,
            transition: 'background 0.15s',
          }}
        >
          Upgrade to Premium
        </Link>
        {isAnon && (
          <Link
            href="/account/sign-in"
            className="brain-sign-in"
            style={{
              fontSize: 11,
              color: C.text.faint,
              textDecoration: 'none',
              letterSpacing: '0.08em',
              fontFamily: FONT,
              transition: 'color 0.15s',
            }}
          >
            Sign in
          </Link>
        )}
      </div>
    </div>
  )
}
