#!/usr/bin/env node
/**
 * inject-premium.mjs — pulls closed-source premium components from the PRIVATE
 * source into this (public) build, so they can be served gated. Runs FIRST in
 * the dev/build chain. See AGENTS.md in the aicanvas-premium repo.
 *
 * Source resolution (in order):
 *   1. PREMIUM_LOCAL_PATH  — a local checkout of aicanvas-premium (dev / offline)
 *   2. GITHUB_PAT_PREMIUM  — HTTPS + read-only PAT shallow-clone (Vercel)
 *   3. neither             — skip cleanly (public forks build free-only)
 *
 * It copies each manifest component into the GITIGNORED components-workspace-premium/,
 * STRIPPING the premium marker (served code must be clean), writes
 * registry-data/_premium.json (feeds the gate's premiumSlugs), and generates the
 * gitignored app/lib/premium-registry.generated.tsx registration shim.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, statSync, cpSync } from 'node:fs'
import { join } from 'node:path'
import { execSync } from 'node:child_process'

const ROOT = process.cwd()
const TARGET = join(ROOT, 'components-workspace-premium')
const SHIM = join(ROOT, 'app/lib/premium-registry.generated.tsx')
const PREMIUM_JSON = join(ROOT, 'registry-data/_premium.json')
// Built from parts so THIS (tracked, public) file never contains the literal
// marker — otherwise the leak guard would flag inject-premium.mjs itself.
const MARKER = ['AICANVAS', 'PREMIUM', 'DO', 'NOT', 'COMMIT'].join('-')

const log = (m) => console.log('[inject-premium] ' + m)

// Always leave a shim behind (empty when no premium) so component-registry.tsx's
// guarded require() resolves on forks / free-only builds.
function writeStubShim() {
  writeFileSync(
    SHIM,
    [
      '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored.',
      "import type { ComponentEntry } from './component-registry'",
      'export const PREMIUM_COMPONENTS: ComponentEntry[] = []',
      '',
    ].join('\n'),
  )
}

// Always start from a clean slate so a removed slug actually disappears.
rmSync(TARGET, { recursive: true, force: true })
rmSync(SHIM, { force: true })
rmSync(PREMIUM_JSON, { force: true })

// ── 1. Resolve the source ──────────────────────────────────────────────────
let source = process.env.PREMIUM_LOCAL_PATH || ''
let tmpClone = ''
if (!source && process.env.GITHUB_PAT_PREMIUM) {
  tmpClone = '/tmp/aicanvas-premium-inject'
  rmSync(tmpClone, { recursive: true, force: true })
  try {
    execSync(
      `git clone --depth 1 https://x-access-token:${process.env.GITHUB_PAT_PREMIUM}@github.com/uiNerd16/aicanvas-premium.git "${tmpClone}"`,
      { stdio: 'pipe' },
    )
  } catch (e) {
    // 3-state PAT: set-but-clone-failed = auth/expiry → FAIL LOUD (never a silent
    // free-only ship to paying customers).
    console.error(
      '\n🚫 [inject-premium] PREMIUM PAT REJECTED — clone failed. Rotate ' +
        'GITHUB_PAT_PREMIUM in Vercel (likely the 90-day expiry).\n' +
        (e.stderr ? e.stderr.toString() : e.message),
    )
    process.exit(1)
  }
  source = tmpClone
}

if (!source) {
  writeStubShim()
  log('no PREMIUM_LOCAL_PATH and no GITHUB_PAT_PREMIUM — free-only build (skip).')
  process.exit(0)
}

// ── 2. Manifest ────────────────────────────────────────────────────────────
let manifest
try {
  manifest = JSON.parse(readFileSync(join(source, 'premium-manifest.json'), 'utf8'))
} catch (e) {
  console.error('[inject-premium] cannot read premium-manifest.json at ' + source + ': ' + e.message)
  process.exit(1)
}
const standalones = Array.isArray(manifest.standalones) ? [...manifest.standalones] : []
if (standalones.length === 0) {
  writeStubShim()
  log('manifest lists 0 standalones — free-only build.')
  process.exit(0)
}

mkdirSync(TARGET, { recursive: true })
mkdirSync(join(ROOT, 'registry-data'), { recursive: true })

// ── 3. Copy each component, stripping the marker ───────────────────────────
const injected = []
for (const slug of standalones) {
  if (!/^[a-z0-9-]+$/.test(slug)) {
    console.error('[inject-premium] invalid slug in manifest: ' + JSON.stringify(slug))
    process.exit(1)
  }
  const srcDir = join(source, 'components-workspace', slug)
  const idx = join(srcDir, 'index.tsx')
  if (!existsSync(idx)) {
    console.error('[inject-premium] manifest slug "' + slug + '" has no components-workspace/' + slug + '/index.tsx')
    process.exit(1)
  }
  const metaPath = join(srcDir, 'meta.json')
  if (!existsSync(metaPath)) {
    console.error('[inject-premium] "' + slug + '" is missing meta.json')
    process.exit(1)
  }
  const meta = JSON.parse(readFileSync(metaPath, 'utf8'))
  if (!meta.name || !meta.description) {
    console.error('[inject-premium] "' + slug + '" meta.json must have name + description')
    process.exit(1)
  }

  const outDir = join(TARGET, slug)
  mkdirSync(outDir, { recursive: true })
  const stripped = readFileSync(idx, 'utf8').split('\n').filter((l) => !l.includes(MARKER)).join('\n')
  writeFileSync(join(outDir, 'index.tsx'), stripped)
  cpSync(metaPath, join(outDir, 'meta.json'))

  const promptsPath = join(srcDir, 'prompts.ts')
  const hasPrompts = existsSync(promptsPath)
  if (hasPrompts) writeFileSync(join(outDir, 'prompts.ts'), readFileSync(promptsPath, 'utf8'))

  injected.push({ slug, meta, hasPrompts })
}

// ── 4. Bijection: manifest ⇄ injected folders ──────────────────────────────
const folderSlugs = readdirSync(TARGET)
  .filter((d) => { try { return statSync(join(TARGET, d, 'index.tsx')).isFile() } catch { return false } })
  .sort()
const manifestSlugs = [...standalones].sort()
if (JSON.stringify(folderSlugs) !== JSON.stringify(manifestSlugs)) {
  console.error('[inject-premium] manifest/folder mismatch:\n  manifest: ' + manifestSlugs.join(', ') + '\n  folders:  ' + folderSlugs.join(', '))
  process.exit(1)
}

// ── 5. _premium.json — feeds the /r gate's premiumSlugs ────────────────────
writeFileSync(PREMIUM_JSON, JSON.stringify({ standalones: manifestSlugs }, null, 2) + '\n')

// ── 6. Registration shim (gitignored) ──────────────────────────────────────
const ident = (s) => 'C_' + s.replace(/[^a-z0-9]/gi, '_')
const imports = [
  '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
  "import dynamic from 'next/dynamic'",
  "import type { ComponentEntry } from './component-registry'",
  "import { componentCodes } from './component-codes.generated'",
]
const decls = []
const entries = []
for (const { slug, meta, hasPrompts } of injected) {
  const v = ident(slug)
  if (hasPrompts) imports.push(`import { prompts as ${v}_p } from '../../components-workspace-premium/${slug}/prompts'`)
  decls.push(`const ${v} = dynamic(() => import('../../components-workspace-premium/${slug}'))`)
  const tags = JSON.stringify(meta.tags ?? [{ label: 'Cards', accent: true }])
  entries.push(
    '  {\n' +
      `    slug: ${JSON.stringify(slug)},\n` +
      `    name: ${JSON.stringify(meta.name)},\n` +
      `    description: ${JSON.stringify(meta.description)},\n` +
      `    tags: ${tags},\n` +
      (meta.image ? `    image: ${JSON.stringify(meta.image)},\n` : '') +
      `    badge: 'Premium',\n` +
      `    PreviewComponent: ${v},\n` +
      `    code: componentCodes[${JSON.stringify(slug)}] ?? '',\n` +
      `    prompts: ${hasPrompts ? `${v}_p` : '{}'},\n` +
      '  },',
  )
}
const shim = [...imports, '', ...decls, '', 'export const PREMIUM_COMPONENTS: ComponentEntry[] = [', ...entries, ']', ''].join('\n')
writeFileSync(SHIM, shim)

if (tmpClone) rmSync(tmpClone, { recursive: true, force: true })
log(`injected ${injected.length} premium component(s): ${injected.map((i) => i.slug).join(', ')}`)
