#!/usr/bin/env node
/**
 * inject-premium.mjs — pulls closed-source premium components from the PRIVATE
 * source into this (public) build, so they can be served gated. Runs FIRST in
 * the dev/build chain. See AGENTS.md in the aicanvas-premium repo.
 *
 * Source resolution (in order):
 *   1. PREMIUM_LOCAL_PATH  — a local checkout of aicanvas-premium (dev / offline)
 *   2. GITHUB_PAT_PREMIUM  — HTTPS + read-only PAT shallow-clone (Vercel)
 *   3. neither             — skip cleanly (public forks build free-only)
 *
 * It copies each manifest component into the GITIGNORED components-workspace-premium/,
 * STRIPPING the premium marker (served code must be clean), writes
 * registry-data/_premium.json (feeds the gate's premiumSlugs), and generates the
 * gitignored app/lib/premium-registry.generated.tsx registration shim.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, statSync, cpSync } from 'node:fs'
import { join } from 'node:path'
import { execSync } from 'node:child_process'

const ROOT = process.cwd()
const TARGET = join(ROOT, 'components-workspace-premium')
const SHIM = join(ROOT, 'app/lib/premium-registry.generated.tsx')
const PREMIUM_JSON = join(ROOT, 'registry-data/_premium.json')
const PREMIUM_LOCK = join(ROOT, 'premium.lock.json')
const BUILD_INFO = join(ROOT, 'app/lib/premium-build-info.generated.ts')

// The EXACT premium commit this public tree builds against (tracked in the public
// repo, bumped only by `npm run publish-premium`). The PAT/Vercel path checks out
// THIS sha instead of floating `main`, making every production build reproducible.
// Dev (PREMIUM_LOCAL_PATH) ignores the pin and uses your working checkout as-is.
let pinnedSha = ''
try {
  pinnedSha = String(JSON.parse(readFileSync(PREMIUM_LOCK, 'utf8')).sha || '').trim()
} catch {
  pinnedSha = ''
}

// Stamp what actually got injected into a gitignored const the /api/premium/health
// route imports — so prod can PROVE it is serving the intended premium commit.
function writeBuildInfo(sha) {
  writeFileSync(
    BUILD_INFO,
    [
      '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
      'export const PREMIUM_BUILD = {',
      `  sha: ${JSON.stringify(sha || null)},`,
      `  pinnedSha: ${JSON.stringify(pinnedSha || null)},`,
      '} as const',
      '',
    ].join('\n'),
  )
}
// Built from parts so THIS (tracked, public) file never contains the literal
// marker — otherwise the leak guard would flag inject-premium.mjs itself.
const MARKER = ['AICANVAS', 'PREMIUM', 'DO', 'NOT', 'COMMIT'].join('-')

const log = (m) => console.log('[inject-premium] ' + m)

// Always leave a shim behind (empty when no premium) so component-registry.tsx's
// guarded require() resolves on forks / free-only builds.
function writeStubShim() {
  writeFileSync(
    SHIM,
    [
      '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored.',
      "import type { ComponentEntry } from './component-registry'",
      'export const PREMIUM_COMPONENTS: ComponentEntry[] = []',
      '',
    ].join('\n'),
  )
}

// Always start from a clean slate so a removed slug actually disappears. Recreate
// the (possibly empty) target dir so the Tailwind `@source` for it always resolves,
// even on free-only builds.
rmSync(TARGET, { recursive: true, force: true })
rmSync(SHIM, { force: true })
rmSync(PREMIUM_JSON, { force: true })
rmSync(BUILD_INFO, { force: true })
mkdirSync(TARGET, { recursive: true })

// ── 1. Resolve the source ──────────────────────────────────────────────────
let source = process.env.PREMIUM_LOCAL_PATH || ''
let tmpClone = ''
if (!source && process.env.GITHUB_PAT_PREMIUM) {
  tmpClone = '/tmp/aicanvas-premium-inject'
  rmSync(tmpClone, { recursive: true, force: true })
  const remote = `https://x-access-token:${process.env.GITHUB_PAT_PREMIUM}@github.com/uiNerd16/aicanvas-premium.git`
  try {
    execSync(`git clone --depth 1 ${remote} "${tmpClone}"`, { stdio: 'pipe' })
  } catch (e) {
    // 3-state PAT: set-but-clone-failed = auth/expiry → FAIL LOUD (never a silent
    // free-only ship to paying customers).
    console.error(
      '\n🚫 [inject-premium] PREMIUM PAT REJECTED — clone failed. Rotate ' +
        'GITHUB_PAT_PREMIUM in Vercel (likely the 90-day expiry).\n' +
        (e.stderr ? e.stderr.toString() : e.message),
    )
    process.exit(1)
  }
  // Pin: build the EXACT committed sha (premium.lock.json), not whatever `main`
  // happens to be right now. Fetch-by-sha works even if the pin isn't the tip, and
  // only succeeds for commits actually pushed to the remote — so an unpushed WIP sha
  // can never build. A missing/unreachable pin FAILS LOUD rather than shipping the
  // wrong premium.
  if (pinnedSha) {
    try {
      execSync(`git -C "${tmpClone}" fetch --depth 1 ${remote} ${pinnedSha}`, { stdio: 'pipe' })
      execSync(`git -C "${tmpClone}" checkout --quiet ${pinnedSha}`, { stdio: 'pipe' })
    } catch (e) {
      console.error(
        '\n🚫 [inject-premium] PINNED PREMIUM COMMIT NOT REACHABLE: ' + pinnedSha + '\n' +
          '   premium.lock.json points at a commit that is not on the aicanvas-premium ' +
          'remote.\n   Fix the pin (usually via `npm run publish-premium`), do not ship.\n' +
          (e.stderr ? e.stderr.toString() : e.message),
      )
      process.exit(1)
    }
    const head = execSync(`git -C "${tmpClone}" rev-parse HEAD`).toString().trim()
    if (head !== pinnedSha) {
      console.error('\n🚫 [inject-premium] pin checkout mismatch: wanted ' + pinnedSha + ' got ' + head)
      process.exit(1)
    }
  } else {
    console.error(
      '\n🚫 [inject-premium] no premium.lock.json pin found for a PAT build. Refusing to ' +
        'build against floating `main`. Commit premium.lock.json (via publish-premium).',
    )
    process.exit(1)
  }
  source = tmpClone
}

if (!source) {
  writeStubShim()
  writeBuildInfo(null)
  log('no PREMIUM_LOCAL_PATH and no GITHUB_PAT_PREMIUM — free-only build (skip).')
  process.exit(0)
}

// The exact commit actually injected: the pinned sha on a PAT build, or your local
// checkout's HEAD in dev. Stamped into build-info so /api/premium/health can prove it.
let builtSha = null
try {
  builtSha = execSync(`git -C "${source}" rev-parse HEAD`).toString().trim()
} catch {
  builtSha = null
}
if (process.env.PREMIUM_LOCAL_PATH && pinnedSha && builtSha && builtSha !== pinnedSha) {
  log(`note: dev checkout ${builtSha.slice(0, 7)} differs from the production pin ${pinnedSha.slice(0, 7)} (expected while iterating).`)
}

// ── 2. Manifest ────────────────────────────────────────────────────────────
let manifest
try {
  manifest = JSON.parse(readFileSync(join(source, 'premium-manifest.json'), 'utf8'))
} catch (e) {
  console.error('[inject-premium] cannot read premium-manifest.json at ' + source + ': ' + e.message)
  process.exit(1)
}
const standalones = Array.isArray(manifest.standalones) ? [...manifest.standalones] : []
if (standalones.length === 0) {
  writeStubShim()
  writeBuildInfo(builtSha)
  log('manifest lists 0 standalones — free-only build.')
  process.exit(0)
}

mkdirSync(TARGET, { recursive: true })
mkdirSync(join(ROOT, 'registry-data'), { recursive: true })

// ── 3. Copy each component, stripping the marker ───────────────────────────
const injected = []
for (const slug of standalones) {
  if (!/^[a-z0-9-]+$/.test(slug)) {
    console.error('[inject-premium] invalid slug in manifest: ' + JSON.stringify(slug))
    process.exit(1)
  }
  const srcDir = join(source, 'components-workspace', slug)
  const idx = join(srcDir, 'index.tsx')
  if (!existsSync(idx)) {
    console.error('[inject-premium] manifest slug "' + slug + '" has no components-workspace/' + slug + '/index.tsx')
    process.exit(1)
  }
  const metaPath = join(srcDir, 'meta.json')
  if (!existsSync(metaPath)) {
    console.error('[inject-premium] "' + slug + '" is missing meta.json')
    process.exit(1)
  }
  const meta = JSON.parse(readFileSync(metaPath, 'utf8'))
  if (!meta.name || !meta.description) {
    console.error('[inject-premium] "' + slug + '" meta.json must have name + description')
    process.exit(1)
  }

  const outDir = join(TARGET, slug)
  mkdirSync(outDir, { recursive: true })
  const stripped = readFileSync(idx, 'utf8').split('\n').filter((l) => !l.includes(MARKER)).join('\n')
  writeFileSync(join(outDir, 'index.tsx'), stripped)
  cpSync(metaPath, join(outDir, 'meta.json'))

  const promptsPath = join(srcDir, 'prompts.ts')
  const hasPrompts = existsSync(promptsPath)
  if (hasPrompts) {
    const strippedPrompts = readFileSync(promptsPath, 'utf8').split('\n').filter((l) => !l.includes(MARKER)).join('\n')
    writeFileSync(join(outDir, 'prompts.ts'), strippedPrompts)
  }

  injected.push({ slug, meta, hasPrompts })
}

// ── 4. Bijection: manifest ⇄ injected folders ──────────────────────────────
const folderSlugs = readdirSync(TARGET)
  .filter((d) => { try { return statSync(join(TARGET, d, 'index.tsx')).isFile() } catch { return false } })
  .sort()
const manifestSlugs = [...standalones].sort()
if (JSON.stringify(folderSlugs) !== JSON.stringify(manifestSlugs)) {
  console.error('[inject-premium] manifest/folder mismatch:\n  manifest: ' + manifestSlugs.join(', ') + '\n  folders:  ' + folderSlugs.join(', '))
  process.exit(1)
}

// ── 5. _premium.json — feeds the /r gate's premiumSlugs ────────────────────
writeFileSync(PREMIUM_JSON, JSON.stringify({ standalones: manifestSlugs }, null, 2) + '\n')

// ── 6. Registration shim (gitignored) ──────────────────────────────────────
const ident = (s) => 'C_' + s.replace(/[^a-z0-9]/gi, '_')
const imports = [
  '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
  "import dynamic from 'next/dynamic'",
  "import type { ComponentEntry } from './component-registry'",
  "import { componentCodes } from './component-codes.generated'",
]
const decls = []
const entries = []
for (const { slug, meta, hasPrompts } of injected) {
  const v = ident(slug)
  if (hasPrompts) imports.push(`import { prompts as ${v}_p } from '../../components-workspace-premium/${slug}/prompts'`)
  decls.push(`const ${v} = dynamic(() => import('../../components-workspace-premium/${slug}'))`)
  const tags = JSON.stringify(meta.tags ?? [{ label: 'Cards', accent: true }])
  entries.push(
    '  {\n' +
      `    slug: ${JSON.stringify(slug)},\n` +
      `    name: ${JSON.stringify(meta.name)},\n` +
      `    description: ${JSON.stringify(meta.description)},\n` +
      `    tags: ${tags},\n` +
      (meta.image ? `    image: ${JSON.stringify(meta.image)},\n` : '') +
      (meta.dualTheme ? '    dualTheme: true,\n' : '') +
      `    badge: 'Premium',\n` +
      `    PreviewComponent: ${v},\n` +
      `    code: componentCodes[${JSON.stringify(slug)}] ?? '',\n` +
      `    prompts: ${hasPrompts ? `${v}_p` : '{}'},\n` +
      '  },',
  )
}
const shim = [...imports, '', ...decls, '', 'export const PREMIUM_COMPONENTS: ComponentEntry[] = [', ...entries, ']', ''].join('\n')
writeFileSync(SHIM, shim)

writeBuildInfo(builtSha)

if (tmpClone) rmSync(tmpClone, { recursive: true, force: true })
log(
  `injected ${injected.length} premium component(s): ${injected.map((i) => i.slug).join(', ')}` +
    (builtSha ? ` @ ${builtSha.slice(0, 7)}` : ''),
)
