// GENERATED from the matrix declarations, then checked by coverage.test.tsx.
// It exists because the gallery is a SERVER component: importing the specs
// there would pull every design-system component (three.js included) into an
// index page that renders none of them. Plain numbers cross that boundary
// for free, and the test fails the moment they stop matching the specs.
export const COMPONENT_COUNTS: Record<string, { variants: number; states: number }> = {
  'alert': { variants: 4, states: 0 },
  'avatar': { variants: 6, states: 1 },
  'badge': { variants: 6, states: 0 },
  'button': { variants: 6, states: 6 },
  'card': { variants: 4, states: 0 },
  'checkbox': { variants: 2, states: 6 },
  'corner-markers': { variants: 5, states: 0 },
  'data-table': { variants: 2, states: 0 },
  'date-range-picker': { variants: 4, states: 3 },
  'drawer': { variants: 4, states: 0 },
  'empty-state': { variants: 2, states: 0 },
  'funnel-chart': { variants: 2, states: 0 },
  'gauge': { variants: 4, states: 0 },
  'heat-grid': { variants: 6, states: 0 },
  'icon-button': { variants: 4, states: 6 },
  'input': { variants: 3, states: 5 },
  'media-card': { variants: 4, states: 0 },
  'metric-chart': { variants: 5, states: 0 },
  'music-player': { variants: 5, states: 0 },
  'nav-item': { variants: 4, states: 5 },
  'panel-header': { variants: 2, states: 0 },
  'panel-menu': { variants: 3, states: 1 },
  'planet': { variants: 4, states: 0 },
  'progress-bar': { variants: 5, states: 0 },
  'radar-chart': { variants: 2, states: 0 },
  'radio': { variants: 2, states: 6 },
  'search-field': { variants: 4, states: 1 },
  'segmented-control': { variants: 4, states: 0 },
  'slider': { variants: 5, states: 3 },
  'spinner': { variants: 4, states: 0 },
  'stat-tile': { variants: 5, states: 0 },
  'table': { variants: 3, states: 2 },
  'tag': { variants: 5, states: 3 },
  'textarea': { variants: 2, states: 5 },
  'toggle': { variants: 2, states: 5 },
  'tooltip': { variants: 4, states: 0 },
  'trend-chart': { variants: 3, states: 0 },
  'user-card': { variants: 4, states: 0 },
  'user-menu': { variants: 4, states: 0 },
  'waveform': { variants: 4, states: 0 },
}
